#!/usr/bin/env bash
# extracting pikachu's info from the .json
set -euo pipefail

JSON_FILE="data.json"

# check if file exists
if [[ ! -f "$JSON_FILE" ]]; then
  echo "Error: $JSON_FILE not found. Run the API fetch script first."
  exit 1
fi

# jq to extract needed fields
name=$(jq -r '.name' "$JSON_FILE" | sed 's/.*/\u&/')  # caps first letter
type=$(jq -r '.types[0].type.name' "$JSON_FILE" | sed 's/.*/\u&/')
formatted_height=$(jq -r '.height' "$JSON_FILE" | awk '{printf "%.1f", $1 * 0.1}')
formatted_weight=$(jq -r '.weight' "$JSON_FILE" | awk '{val=$1*0.1; if (val == int(val)) printf "%d", val; else printf "%.1f", val}')

#formatted output
echo ["$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."]

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
